#pragma once

#define AUTO_SHIFT_TIMEOUT 220
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_TAB
#define AUTO_SHIFT_NO_SETUP

#define TAPPING_TERM 180
#define QUICK_TAP_TERM 0

#define COMBO_TERM 40
#define COMBO_TERM_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 0

#define ONESHOT_TIMEOUT 1000

#define OLED_TIMEOUT 30000
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_OLED_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#define RGB_MATRIX_HUE_STEP 8
#define RGB_MATRIX_SAT_STEP 8
#define RGB_MATRIX_VAL_STEP 8
#define RGB_MATRIX_SPD_STEP 10

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_ALL
